blog/urls.py
from django.urls import path
from . import views

app_name ='blog'

urlpatterns = [   
   path('',views.index, name='index'),
   path('post_list/',views.post_list, name='post_list'),
   #path('','django.views.generic.simple.direct_to_template',{'template':'layout.html'},name='layout'),
   path('post_detail<int:pk>/',views.post_detail, name ="post_detail"),
  # path('',views.main, name='main'),
]

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    photo = models.ImageField()    
    is_public = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

# Create your views here.

def post_list(request):
    post_list = Post.objects.all()
    return render(request, 'blog/post_list.html',{
        'post_list':post_list,
    })
    
def post_detail(request,pk):
    post = get_object_or_404(Post,pk=pk)
    return render(request,'blog/post_detail.html',{
        'post':post,
    })

def index(request):
    post_list = Post.objects.all()
    return render(request,'blog/post_main.html',{
        'post_list':post_list,
    })

blog/templates/blog/index.html
{% load staticfiles %}

<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}GT&P{% endblock %}</title>
    
    {# <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"/> #}
    <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootswatch/4.1.1/flatly/bootstrap.min.css"/>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>
<body>
    
    <div class="container">
        <header class="blog-header py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 pt-1">
                    <img src="{% static "img/gtnp.png" %}" >
              {#}  <a class="text-muted" href="#">Subscribe</a> #}
            </div>
            <div class="col-4 text-center">
                <a class="blog-header-logo text-dark" href="{% url "blog:post_detail" '3' %}"><h1>지티앤피(주) </h1></a>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
                <a class="text-muted" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
                </a>
                <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a>
            </div>
            </div>
        </header>
    
        <div class="nav-scroller py-1 mb-2">
            <nav class="nav d-flex justify-content-between">
            <a class="p-2 text-muted" href="#">회사소개</a>
            <a class="p-2 text-muted" href="">경영이념</a>
            <a class="p-2 text-muted" href="">특허권</a>
            <a class="p-2 text-muted" href="">중문반자동</a>
            <a class="p-2 text-muted" href="">로봇</a>
            <a class="p-2 text-muted" href="">IoT모니터링</a>
            <a class="p-2 text-muted" href="">IoT이륜차</a>
            <a class="p-2 text-muted" href="">블라인더</a>
            <a class="p-2 text-muted" href="">공장자동화</a>
            <a class="p-2 text-muted" href="}">양식장</a>
            <a class="p-2 text-muted" href="">온도제어</a>
            <a class="p-2 text-muted" href="">수중드론</a>
            <a class="p-2 text-muted" href="}">선박</a>
            <a class="p-2 text-muted" href="">History</a>            
            </nav>
    </div>    

    <hr/>

    2018 &copy; Moon & Sun

    {# <script src="//code.jquery.com/jquery-2.2.4.min.js"></script> #}
    <script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

</body>

</html>

blog/templates/blog/layout.html
{% load staticfiles %}

<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}GT&P{% endblock %}</title>
    
    {# <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"/> #}
    <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootswatch/4.1.1/flatly/bootstrap.min.css"/>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>
<body>
    
    <div class="container">
        <header class="blog-header py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 pt-1">
                    <img src="{% static "img/gtnp.png" %}" >
              {#}  <a class="text-muted" href="#">Subscribe</a> #}
            </div>
            <div class="col-4 text-center">
                <a class="blog-header-logo text-dark" href="{% url "blog:post_detail" '3' %}"><h1>지티앤피(주) </h1></a>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
                <a class="text-muted" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
                </a>
                <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a>
            </div>
            </div>
        </header>
    
        <div class="nav-scroller py-1 mb-2">
            <nav class="nav d-flex justify-content-between">
            <a class="p-2 text-muted" href="{% url "blog:post_detail" '3' %}">회사소개</a>
            <a class="p-2 text-muted" href="{% url "blog:post_detail" '5' %}">경영이념</a>
            <a class="p-2 text-muted" href="{% url "blog:post_detail" '6' %}">특허권</a>
            <a class="p-2 text-muted" href="{% url "blog:post_detail" '10' %}">중문반자동</a>
            <a class="p-2 text-muted" href="{% url "blog:post_detail" '12' %}">로봇</a>
            <a class="p-2 text-muted" href="{% url "blog:post_detail" '18' %}">IoT모니터링</a>
            <a class="p-2 text-muted" href="{% url "blog:post_detail" '19' %}">IoT이륜차</a>
            <a class="p-2 text-muted" href="{% url "blog:post_detail" '29' %}">블라인더</a>
            <a class="p-2 text-muted" href="{% url "blog:post_detail" '28' %}">공장자동화</a>
            <a class="p-2 text-muted" href="{% url "blog:post_detail" '27' %}">양식장</a>
            <a class="p-2 text-muted" href="{% url "blog:post_detail" '24' %}">온도제어</a>
            <a class="p-2 text-muted" href="{% url "blog:post_detail" '22' %}">수중드론</a>
            <a class="p-2 text-muted" href="{% url "blog:post_detail" '11' %}">선박</a>
            <a class="p-2 text-muted" href="{% url "blog:post_list" %}">History</a>            
            </nav>
    </div>
    


    {% block content %}
    {% endblock %}

    <hr/>

    2018 &copy; Moon & Sun

    {# <script src="//code.jquery.com/jquery-2.2.4.min.js"></script> #}
    <script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

</body>

</html>

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% block title %}{{post.title}}{% endblock %}

{%block extra_head %}
<style>
    .post_photo{
        max-width: 100%;
    }
</style>
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
                <div class="panel panel-default"> 
                    <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2 class="panel-title"> {{ post.title}} </h2>
                    </div>
                    <div class="panel-body">
                        {% if post.photo %}
                            <img src = "{{ post.photo.url }}" class="post_photo" />
                        {% endif %}
                        <hr/>
                    
                        {{ post.content | linebreaks }}
                    </div>
                </div>
                <div class="panel panel-default">                    
                    <div class="panel-footer">
                        <a href="{% url "blog:index" %}" class="btn btn-default"> 목록으로</a>
                    </div>
                </div>
        </div>
    </div>
</div>

    
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}


{% block content %}

<h1> History </h1>
    
{% for post in post_list %}   
<li>
    <a href="{% url "blog:post_detail" post.pk %}">        
        {{post.title}}  
    </a> 
</li>                        
{% endfor %}          

{% endblock %}

blog/templates/blog/post_main.html
{% extends "blog/layout.html" %}
{% load staticfiles %}   

{% block content %}
    <img src="{% static "img/main.png" %}" >    
{% endblock %}